site_name: Kaijing's Tech Blog
theme:
    name: dracula
    logo: assets/logo.jpg
    favicon: assets/logo.jpg
nav:
    - Home: index.md
    - ComputerScience: 
      - ComputerScience/深度学习.md
    - Mathematics: 
      - Mathematics/高等数学.md
    - Physics:
      - Physics/量子力学.md
    - Psychology:
      - Psychology/心理学.md
    - Language: 
      - Language/雅思.md
    - Life:
      - Life/2024.11.17成长记录.md

